canceled: will not work
won't work as there are too many differences with the mainline kernel

diff --git a/rknpu-driver/pkg.yaml b/rknpu-driver/pkg.yaml
--- a/rknpu-driver/pkg.yaml
+++ b/rknpu-driver/pkg.yaml
@@ -16,16 +16,16 @@ steps:
       - |
         tar xf linux-rockchip.tar.gz --strip-components=1
       - |
-        find drivers/ -name 'Makefile' -exec grep -l CONFIG_ROCKCHIP_RKNPU {} \; | xargs -L1 sed -i 's/$(CONFIG_ROCKCHIP_RKNPU)/m/g'
+        for patch in $(find /pkg/patches -type f -name "*.patch" | sort); do
+          patch -p1 < $patch || (echo "Failed to apply patch $patch" && exit 1)
+          echo "Applied patch $patch"
+        done
+      # - |
+      #   find drivers/ -name 'Makefile' -exec grep -l CONFIG_ROCKCHIP_RKNPU {} \; | xargs -L1 sed -i 's/$(CONFIG_ROCKCHIP_RKNPU)/m/g'
     build:
       - |
         cd drivers/rknpu
         make -C /src M=$(pwd) modules -j $(nproc)
-        find . -name '*.ko' || {
-          echo "ERROR: No kernel modules found in drivers/rknpu"
-          exit 1
-        }
-        ls -la
     install:
       - |
         cd drivers/rknpu
